[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts/ =lib/chainlink-brownie-contracts/contracts/",
    "@solmate=lib/solmate/src/tokens "
]
dotenv = ".env"
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
[profile.ci]
sizes = true
ignored_contracts = ["VRFCoordinatorV2_5Mock"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
